apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  ports:
  - port: 2368
  type: LoadBalancer
  selector:
    app: ghost #match pods with label app:ghost
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  selector:
    matchLabels: # matches the pod template (pod) with app:ghost
      app: ghost
  strategy:
    type: Recreate
  template: # this is a pod template
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:2
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-pv-storage
          mountPath: /var/lib/ghost/content
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
      volumes:
      - name: ghost-pv-storage
        persistentVolumeClaim:
          claimName: ghost-pv-claim