apiVersion: v1
kind: Service
metadata:
  name: ghost-service-another
  labels:
    app: ghost-another
spec:
  ports:
  - port: 2368
  type: LoadBalancer
  selector:
    app: ghost-another
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ghost-another-deployment
spec:
  selector:
    matchLabels:
      app: ghost-another
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost-another
    spec:
      containers:
      - name: ghost-another
        image: ghost:2
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-pv-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-pv-storage
        persistentVolumeClaim:
          claimName: ghost-pv-claim


