apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-ghost-storage
  labels:
    type: local-ghost
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/ghost-tmp